//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ad_mock_register
    {
        public int adloginid { get; set; }
        public string adlogin_name { get; set; }
        public string adlogin_password { get; set; }
        public string adlogin_emailid { get; set; }
        public string adlogin_mobileno { get; set; }
        public System.DateTime adlogin_created_on { get; set; }
        public string adlogin_status { get; set; }
        public string adlogin_mobileverified { get; set; }
    }
}
