//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollegeImages
    {
        public long collimg_Id { get; set; }
        public long collimg_CollegeId { get; set; }
        public string collimg_ImageName { get; set; }
        public Nullable<System.DateTime> collimg_CreatedDate { get; set; }
    
        public virtual Colleges Colleges { get; set; }
    }
}
