//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollegeCoursesRelation
    {
        public long collcrsrel_Id { get; set; }
        public long collcrsrel_CollegeId { get; set; }
        public long collcrsrel_CollegeCourseId { get; set; }
        public string collcrsrel_Seats { get; set; }
        public string collcrsrel_FeeDetails { get; set; }
        public Nullable<System.DateTime> collcrsrel_CreatedDate { get; set; }
        public Nullable<int> collcrsrel_CreatedBy { get; set; }
        public Nullable<System.DateTime> collcrsrel_UpdatedDate { get; set; }
        public Nullable<int> collcrsrel_UpdatedBy { get; set; }
        public string collcrsrel_Mode { get; set; }
        public string collcrsrel_Duration { get; set; }
    
        public virtual CollegeCourses CollegeCourses { get; set; }
        public virtual Colleges Colleges { get; set; }
    }
}
