//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollegeCourses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CollegeCourses()
        {
            this.shub_collegecoursesrelation = new HashSet<CollegeCoursesRelation>();
        }
    
        public long colcrs_Id { get; set; }
        public string colcrs_Name { get; set; }
        public string colcrs_UrlKeyword { get; set; }
        public Nullable<long> colcrs_CourseType { get; set; }
        public Nullable<long> colcrs_CourseLevel { get; set; }
        public Nullable<long> colcrs_DegreeType { get; set; }
        public string colcrs_Logo { get; set; }
        public string colcrs_CoverPic { get; set; }
        public string colcrs_ShortDescription { get; set; }
        public string colcrs_Description { get; set; }
        public string colcrs_IsTrending { get; set; }
        public string colcrs_EligibilityCriteria { get; set; }
        public string colcrs_Duration { get; set; }
        public string colcrs_ExamType { get; set; }
        public string colcrs_FeeDesc { get; set; }
        public string colcrs_FeeMinimum { get; set; }
        public string colcrs_FeeMaximum { get; set; }
        public string colcrs_AdmissionProcess { get; set; }
        public string colcrs_TopEntranceTest { get; set; }
        public string colcrs_SelectionProcess { get; set; }
        public string colcrs_LateralEntry { get; set; }
        public string colcrs_AcademicOptions { get; set; }
        public string colcrs_SalaryOfferedFreshes { get; set; }
        public string colcrs_JobProfile { get; set; }
        public string colcrs_JobProspects { get; set; }
        public string colcrs_Top5Recruiters { get; set; }
        public Nullable<System.DateTime> colcrs_CreatedDate { get; set; }
        public Nullable<System.DateTime> colcrs_ModifiedDate { get; set; }
        public Nullable<int> colcrs_CreatedBy { get; set; }
        public Nullable<int> colcrs_UpdatedBy { get; set; }
        public string colcrs_Status { get; set; }
        public string colcrs_IsFeatured { get; set; }
        public string colcrs_IsTop { get; set; }
    
        public virtual DropdownTypes CourseLevelDropdownTypes { get; set; }
        public virtual DropdownTypes CourseTypeDropdownTypes { get; set; }
        public virtual DropdownTypes DegreeTypeDropdownTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollegeCoursesRelation> shub_collegecoursesrelation { get; set; }
    }
}
