//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamCourses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamCourses()
        {
            this.MockTests = new HashSet<MockTests>();
        }
    
        public long exmcrs_Id { get; set; }
        public string exmcrs_Name { get; set; }
        public string exmcrs_UrlKeyword { get; set; }
        public string exmcrs_Description { get; set; }
        public long exmcrs_ExamType { get; set; }
        public long exmcrs_ExamStream { get; set; }
        public long exmcrs_ExamLevel { get; set; }
        public long exmcrs_ExamMode { get; set; }
        public string exmcrs_Registration { get; set; }
        public string exmcrs_Eligibility { get; set; }
        public string exmcrs_PatternSyllabus { get; set; }
        public string exmcrs_PreparationTips { get; set; }
        public string exmcrs_AdmitCard { get; set; }
        public string exmcrs_Results { get; set; }
        public string exmcrs_ImportantDates { get; set; }
        public Nullable<System.DateTime> exmcrs_ApplicationStartDate { get; set; }
        public Nullable<System.DateTime> exmcrs_ApplicationEndDate { get; set; }
        public Nullable<System.DateTime> exmcrs_ExamDate { get; set; }
        public string exmcrs_Counselling { get; set; }
        public string exmcrs_RelatedArticles { get; set; }
        public Nullable<System.DateTime> exmcrs_CreatedDate { get; set; }
        public Nullable<System.DateTime> exmcrs_UpdatedDate { get; set; }
        public Nullable<int> exmcrs_CreatedBy { get; set; }
        public Nullable<int> exmcrs_UpdatedBy { get; set; }
        public string exmcrs_Logo { get; set; }
        public string exmcrs_Status { get; set; }
        public string exmcrs_PackageValidity { get; set; }
        public string exmcrs_Price { get; set; }
        public string exmcrs_OfferPrice { get; set; }
        public string exmcrs_FreeTestsCount { get; set; }
        public string exmcrs_PaidTestsCount { get; set; }
    
        public virtual DropdownTypes ExamLevels { get; set; }
        public virtual DropdownTypes ExamModes { get; set; }
        public virtual DropdownTypes ExamStreams { get; set; }
        public virtual DropdownTypes ExamTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MockTests> MockTests { get; set; }
    }
}
