//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class his_shub_maincourses
    {
        public long course_his_Id { get; set; }
        public string course_his_TransactionType { get; set; }
        public Nullable<System.DateTime> course_his_CreatedDate { get; set; }
        public long MainCourseId { get; set; }
        public string Name { get; set; }
        public string UrlKeyword { get; set; }
        public string Description { get; set; }
        public string Syllabus { get; set; }
        public string Eligibility { get; set; }
        public string IsInTopList { get; set; }
        public string IsFeatured { get; set; }
        public string IsTrending { get; set; }
        public Nullable<long> Stream { get; set; }
        public string Logo { get; set; }
        public string Status { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescription { get; set; }
        public Nullable<System.DateTime> course_CreatedDate { get; set; }
        public Nullable<System.DateTime> course_UpdatedDate { get; set; }
    }
}
