//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class his_shub_institutions
    {
        public long ins_his_Id { get; set; }
        public string ins_his_TransactionType { get; set; }
        public Nullable<System.DateTime> ins_his_CreatedDate { get; set; }
        public long InstitutionId { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string UrlKeyword { get; set; }
        public string About { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Area { get; set; }
        public string City { get; set; }
        public string MapLocation { get; set; }
        public string Pincode { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string LandLine { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Website { get; set; }
        public string Status { get; set; }
        public string IsTop { get; set; }
        public string IsFeatured { get; set; }
        public string IsTrending { get; set; }
        public string JobAssistance { get; set; }
        public string TrainingSatisfaction { get; set; }
        public string JobGurarantee { get; set; }
        public string IsVerified { get; set; }
        public string Logo { get; set; }
        public string Broucher { get; set; }
        public Nullable<System.DateTime> ins_CreatedDate { get; set; }
        public Nullable<System.DateTime> ins_UpdatedDate { get; set; }
    }
}
