//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class his_shub_institutioncourses
    {
        public long inscrs_his_Id { get; set; }
        public string inscrs_his_TransactionType { get; set; }
        public Nullable<System.DateTime> inscrs_his_CreatedDate { get; set; }
        public long InstitutionCourseId { get; set; }
        public long InstitutionId { get; set; }
        public long CourseId { get; set; }
        public string CourseFee { get; set; }
        public string Duration { get; set; }
        public string ClassRoomTraining { get; set; }
        public string OnlineTraining { get; set; }
        public string Proxy { get; set; }
        public string CorporateTraining { get; set; }
        public string Internship { get; set; }
        public Nullable<System.DateTime> inscrs_CreatedDate { get; set; }
        public Nullable<System.DateTime> inscrs_UpdatedDate { get; set; }
    }
}
