//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class his_shub_institutioncoursestrainingmodes
    {
        public long trnmd_his_Id { get; set; }
        public string trnmd_his_TransactionType { get; set; }
        public Nullable<System.DateTime> trnmd_his_CreatedDate { get; set; }
        public long InstitutionCourseTrainingModesId { get; set; }
        public Nullable<long> CourseId { get; set; }
        public Nullable<long> TrainingModeId { get; set; }
    }
}
