//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class his_shub_colleges
    {
        public long coll_his_Id { get; set; }
        public string coll_his_TransactionType { get; set; }
        public Nullable<System.DateTime> coll_his_CreatedDate { get; set; }
        public long coll_ID { get; set; }
        public string coll_Name { get; set; }
        public string coll_UrlKeyword { get; set; }
        public long coll_Type { get; set; }
        public string coll_Description { get; set; }
        public string coll_Logo { get; set; }
        public string coll_CoverPic { get; set; }
        public string coll_Address { get; set; }
        public string coll_Knownas { get; set; }
        public string coll_AcademicDepartments { get; set; }
        public string coll_AcademicCentres { get; set; }
        public string coll_FacultyNo { get; set; }
        public string coll_StudentsIntake { get; set; }
        public string coll_StudentsDiversity { get; set; }
        public string coll_FacultytoStudentRatio { get; set; }
        public string coll_AnnualExpenditure { get; set; }
        public string coll_ResearchDetails { get; set; }
        public string coll_TypeOfInstitute { get; set; }
        public string coll_SubType { get; set; }
        public string coll_4YearsDegree { get; set; }
        public string coll_5YearsDegree { get; set; }
        public string coll_3YearsDegree { get; set; }
        public string coll_ModeOfAdmission { get; set; }
        public string coll_FeesStructure { get; set; }
        public string coll_HostelFee { get; set; }
        public string coll_FeeWaivers { get; set; }
        public string coll_Scholarships { get; set; }
        public string coll_CampusFacilities { get; set; }
        public string coll_Rankings { get; set; }
        public string coll_Connectivity { get; set; }
        public string coll_AddressLine1 { get; set; }
        public string coll_AddressLine2 { get; set; }
        public string coll_AddressLine3 { get; set; }
        public string coll_City { get; set; }
        public string coll_State { get; set; }
        public string coll_Pincode { get; set; }
        public string coll_Country { get; set; }
        public string coll_Location { get; set; }
        public string coll_Approval { get; set; }
        public string coll_Accreditation { get; set; }
        public string coll_Ownership { get; set; }
        public string coll_EducationStatus { get; set; }
        public string coll_Website { get; set; }
        public string coll_Phone1 { get; set; }
        public string coll_Phone2 { get; set; }
        public string coll_Email1 { get; set; }
        public string coll_Email2 { get; set; }
        public string coll_Facebook { get; set; }
        public string coll_Twitter { get; set; }
        public string coll_Youtube { get; set; }
        public string coll_HighestPackage { get; set; }
        public string coll_AveragePackage { get; set; }
        public string coll_LowestPackage { get; set; }
        public string coll_InternationalPackage { get; set; }
        public string coll_Recruiters { get; set; }
        public string coll_EstablishedYear { get; set; }
        public string coll_CampusSize { get; set; }
        public Nullable<System.DateTime> coll_CreatedDate { get; set; }
        public string coll_Status { get; set; }
        public string coll_IsTrending { get; set; }
        public string coll_IsFeatured { get; set; }
        public string coll_IsTop { get; set; }
        public Nullable<System.DateTime> coll_UpdatedDate { get; set; }
        public Nullable<int> coll_CreatedBy { get; set; }
        public Nullable<int> coll_UpdatedBy { get; set; }
    }
}
