//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class his_shub_dropdowntypes
    {
        public long type_his_Id { get; set; }
        public string type_his_TransactionType { get; set; }
        public long DropdownTypeId { get; set; }
        public string GroupName { get; set; }
        public string TypeValue { get; set; }
        public string TypeValueUrlKeyword { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
