//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class his_shub_collegefacilities
    {
        public long coll_his_Id { get; set; }
        public string coll_his_TransactionType { get; set; }
        public Nullable<System.DateTime> coll_his_CreatedDate { get; set; }
        public long collfac_Id { get; set; }
        public long collfac_CollegeId { get; set; }
        public long collfac_FacilityId { get; set; }
        public Nullable<System.DateTime> collfac_CreatedDate { get; set; }
        public Nullable<int> collfac_CreatedBy { get; set; }
    }
}
