//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institutions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Institutions()
        {
            this.MainCourses = new HashSet<InstitutionCourses>();
            this.Addresses = new HashSet<Addresses>();
            this.NewsAlerts = new HashSet<NewsAlerts>();
        }
    
        public long InstitutionId { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string UrlKeyword { get; set; }
        public string About { get; set; }
        public string Address { get; set; }
        public string Area { get; set; }
        public string City { get; set; }
        public string Pincode { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string LandLine { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Website { get; set; }
        public string IsTop { get; set; }
        public string IsFeatured { get; set; }
        public string IsTrending { get; set; }
        public string Logo { get; set; }
        public string Broucher { get; set; }
        public string Status { get; set; }
        public string MapLocation { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string JobAssistance { get; set; }
        public string TrainingSatisfaction { get; set; }
        public string JobGurarantee { get; set; }
        public string IsVerified { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstitutionCourses> MainCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Addresses> Addresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsAlerts> NewsAlerts { get; set; }
    }
}
