//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstitutionCourses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstitutionCourses()
        {
            this.InstitutionCourseTrainingModes = new HashSet<InstitutionCourseTrainingModes>();
        }
    
        public long InstitutionCourseId { get; set; }
        public long InstitutionId { get; set; }
        public long CourseId { get; set; }
        public string CourseFee { get; set; }
        public string Duration { get; set; }
        public string ClassRoomTraining { get; set; }
        public string OnlineTraining { get; set; }
        public string Proxy { get; set; }
        public string CorporateTraining { get; set; }
        public string Internship { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual MainCourses MainCourses { get; set; }
        public virtual Institutions Institutions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstitutionCourseTrainingModes> InstitutionCourseTrainingModes { get; set; }
    }
}
