//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstitutionCourseTrainingModes
    {
        public long InstitutionCourseTrainingModesId { get; set; }
        public Nullable<long> CourseId { get; set; }
        public Nullable<long> TrainingModeId { get; set; }
    
        public virtual DropdownTypes TrainingModes { get; set; }
        public virtual InstitutionCourses InstitutionCourses { get; set; }
    }
}
