//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobAlerts
    {
        public long JobId { get; set; }
        public long JobType { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public string JD { get; set; }
        public string Company { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Pincode { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string CompanyLogo { get; set; }
        public string job_Website { get; set; }
        public string job_Domain { get; set; }
        public string job_Designation { get; set; }
        public string job_EligibilityCriteria { get; set; }
        public string job_CtcAnnum { get; set; }
        public string job_BondPeriod { get; set; }
        public string job_SkillsRequired { get; set; }
        public string job_SelectionProcess { get; set; }
        public string job_AdditionalInformation { get; set; }
        public string job_ContactInfo { get; set; }
        public Nullable<System.DateTime> job_LastDateToApply { get; set; }
    
        public virtual DropdownTypes DropownTypes { get; set; }
    }
}
