//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainCourses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MainCourses()
        {
            this.Institutions = new HashSet<InstitutionCourses>();
            this.QuestionPapers = new HashSet<QuestionPapers>();
            this.SectionCourses = new HashSet<SectionCourses>();
            this.NewsAlerts = new HashSet<NewsAlerts>();
        }
    
        public long MainCourseId { get; set; }
        public string Name { get; set; }
        public string UrlKeyword { get; set; }
        public string Description { get; set; }
        public string IsInTopList { get; set; }
        public string IsFeatured { get; set; }
        public string IsTrending { get; set; }
        public Nullable<long> Stream { get; set; }
        public string Logo { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescription { get; set; }
        public string Status { get; set; }
        public string Syllabus { get; set; }
        public string Eligibility { get; set; }
    
        public virtual DropdownTypes DropdownTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstitutionCourses> Institutions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionPapers> QuestionPapers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SectionCourses> SectionCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsAlerts> NewsAlerts { get; set; }
    }
}
