//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MockTestQuestions
    {
        public long QuestionID { get; set; }
        public long MockTestId { get; set; }
        public string QuestionText { get; set; }
        public string AnswerOption { get; set; }
        public string OptionA { get; set; }
        public string OptionAImage { get; set; }
        public string OptionB { get; set; }
        public string OptionBImage { get; set; }
        public string OptionC { get; set; }
        public string OptionCImage { get; set; }
        public string OptionD { get; set; }
        public string OptionDImage { get; set; }
        public string Explanation { get; set; }
        public string ExplanationImage { get; set; }
        public string QuestionImage { get; set; }
        public string OptionE { get; set; }
        public string OptionEImage { get; set; }
        public string AnswerOption2 { get; set; }
        public string AnswerOption3 { get; set; }
    
        public virtual MockTests MockTests { get; set; }
    }
}
