//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MockTests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MockTests()
        {
            this.MockTestQuestions = new HashSet<MockTestQuestions>();
        }
    
        public long MockTestId { get; set; }
        public long CourseId { get; set; }
        public string Difficulty { get; set; }
        public string Description { get; set; }
        public string MaximumQuestions { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Title { get; set; }
        public Nullable<long> Type { get; set; }
        public string Subject { get; set; }
        public string Chapter { get; set; }
        public string Year { get; set; }
        public string QuestionMaxTime { get; set; }
        public string TestMaxTime { get; set; }
        public string Price { get; set; }
        public string DiscountOfferPrice { get; set; }
        public string CouponCodeOffer { get; set; }
        public string FreePaidTest { get; set; }
        public string GovtPrivateExam { get; set; }
        public string Language { get; set; }
        public double mocktest_Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MockTestQuestions> MockTestQuestions { get; set; }
        public virtual ExamCourses ExamCourses { get; set; }
        public virtual DropdownTypes shub_dropdowntypes { get; set; }
    }
}
