//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionPapers
    {
        public long QuestionPaperId { get; set; }
        public long CourseId { get; set; }
        public string Title { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
        public string Filename { get; set; }
    
        public virtual MainCourses MainCourses { get; set; }
    }
}
