//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class rslt_DistrictsMaster
    {
        public int dstrct_Sno { get; set; }
        public string dstrct_ID { get; set; }
        public string dstrct_Name { get; set; }
        public Nullable<int> dstrct_ExamType { get; set; }
        public System.DateTime dstrct_CreatedDate { get; set; }
        public Nullable<System.DateTime> dstrct_UpdatedDate { get; set; }
    }
}
