//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class rslt_UploadedResults
    {
        public int upld_Sno { get; set; }
        public int upld_ExamType { get; set; }
        public string upld_ExamYear { get; set; }
        public string upld_FileName { get; set; }
        public string upld_Status { get; set; }
        public Nullable<System.DateTime> upld_CreatedDate { get; set; }
        public Nullable<System.DateTime> upld_UpdatedDate { get; set; }
        public string upld_ExamMonth { get; set; }
        public string upld_ResultReleaseDate { get; set; }
    }
}
