//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class rslt_IntermediateYear2Voc_Temp
    {
        public int inter2voc_Sno { get; set; }
        public int inter2voc_ExamType { get; set; }
        public string inter2voc_ExamYear { get; set; }
        public string inter2voc_FullRecord { get; set; }
        public string inter2voc_ROLLNO { get; set; }
        public string inter2voc_DIST { get; set; }
        public string inter2voc_CNAME { get; set; }
        public string inter2voc_COURSE { get; set; }
        public string inter2voc_YR1FPC1 { get; set; }
        public string inter2voc_YR1FMKS1 { get; set; }
        public string inter2voc_YR1FIND1 { get; set; }
        public string inter2voc_YR1FRES1 { get; set; }
        public string inter2voc_YR1FPC2 { get; set; }
        public string inter2voc_YR1FMKS2 { get; set; }
        public string inter2voc_YR1FIND2 { get; set; }
        public string inter2voc_YR1FRES2 { get; set; }
        public string inter2voc_YR1TPC1 { get; set; }
        public string inter2voc_YR1TMKS1 { get; set; }
        public string inter2voc_YR1TIND1 { get; set; }
        public string inter2voc_YR1TRES1 { get; set; }
        public string inter2voc_YR1TPC2 { get; set; }
        public string inter2voc_YR1TMKS2 { get; set; }
        public string inter2voc_YR1TIND2 { get; set; }
        public string inter2voc_YR1TRES2 { get; set; }
        public string inter2voc_YR1TPC3 { get; set; }
        public string inter2voc_YR1TMKS3 { get; set; }
        public string inter2voc_YR1TIND3 { get; set; }
        public string inter2voc_YR1TRES3 { get; set; }
        public string inter2voc_YR1PPC1 { get; set; }
        public string inter2voc_YR1PMKS1 { get; set; }
        public string inter2voc_YR1PIND1 { get; set; }
        public string inter2voc_YR1PRES1 { get; set; }
        public string inter2voc_YR1PPC2 { get; set; }
        public string inter2voc_YR1PMKS2 { get; set; }
        public string inter2voc_YR1PIND2 { get; set; }
        public string inter2voc_YR1PRES2 { get; set; }
        public string inter2voc_YR1PPC3 { get; set; }
        public string inter2voc_YR1PMKS3 { get; set; }
        public string inter2voc_YR1PIND3 { get; set; }
        public string inter2voc_YR1PRES3 { get; set; }
        public string inter2voc_YR1PPC4 { get; set; }
        public string inter2voc_YR1PMKS4 { get; set; }
        public string inter2voc_YR1PIND4 { get; set; }
        public string inter2voc_YR1PRES4 { get; set; }
        public string inter2voc_YR2FPC1 { get; set; }
        public string inter2voc_YR2FMKS1 { get; set; }
        public string inter2voc_YR2FIND1 { get; set; }
        public string inter2voc_YR2FRES1 { get; set; }
        public string inter2voc_YR2FPC2 { get; set; }
        public string inter2voc_YR2FMKS2 { get; set; }
        public string inter2voc_YR2FIND2 { get; set; }
        public string inter2voc_YR2FRES2 { get; set; }
        public string inter2voc_YR2TPC1 { get; set; }
        public string inter2voc_YR2TMKS1 { get; set; }
        public string inter2voc_YR2TIND1 { get; set; }
        public string inter2voc_YR2TRES1 { get; set; }
        public string inter2voc_YR2TPC2 { get; set; }
        public string inter2voc_YR2TMKS2 { get; set; }
        public string inter2voc_YR2TIND2 { get; set; }
        public string inter2voc_YR2TRES2 { get; set; }
        public string inter2voc_YR2TPC3 { get; set; }
        public string inter2voc_YR2TMKS3 { get; set; }
        public string inter2voc_YR2TIND3 { get; set; }
        public string inter2voc_YR2TRES3 { get; set; }
        public string inter2voc_YR2PPC1 { get; set; }
        public string inter2voc_YR2PMKS1 { get; set; }
        public string inter2voc_YR2PIND1 { get; set; }
        public string inter2voc_YR2PRES1 { get; set; }
        public string inter2voc_YR2PPC2 { get; set; }
        public string inter2voc_YR2PMKS2 { get; set; }
        public string inter2voc_YR2PIND2 { get; set; }
        public string inter2voc_YR2PRES2 { get; set; }
        public string inter2voc_YR2PPC3 { get; set; }
        public string inter2voc_YR2PMKS3 { get; set; }
        public string inter2voc_YR2PIND3 { get; set; }
        public string inter2voc_YR2PRES3 { get; set; }
        public string inter2voc_YR2PPC4 { get; set; }
        public string inter2voc_YR2PMKS4 { get; set; }
        public string inter2voc_YR2PIND4 { get; set; }
        public string inter2voc_YR2PRES4 { get; set; }
        public string inter2voc_TOTAL { get; set; }
        public string inter2voc_RESULT { get; set; }
        public System.DateTime inter2voc_CreatedDate { get; set; }
    }
}
