//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class rslt_CourseTypes
    {
        public int corseTyp_Sno { get; set; }
        public string corseTyp_ID { get; set; }
        public string corseTyp_Name { get; set; }
        public string corseTyp_State { get; set; }
        public string corseTyp_ExamType { get; set; }
        public System.DateTime corseTyp_CreatedDate { get; set; }
        public Nullable<System.DateTime> corseTyp_UpdatedDate { get; set; }
        public string corseTyp_University { get; set; }
    }
}
