//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class rslt_IntermediateYear2Regular_Temp
    {
        public int inter2reg_Sno { get; set; }
        public int inter2reg_ExamType { get; set; }
        public string inter2reg_ExamYear { get; set; }
        public string inter2reg_FullRecord { get; set; }
        public string inter2reg_ROLLNO { get; set; }
        public string inter2reg_DIST { get; set; }
        public string inter2reg_CNAME { get; set; }
        public string inter2reg_YR1PC1 { get; set; }
        public string inter2reg_YR1MKS1 { get; set; }
        public string inter2reg_YR1IND1 { get; set; }
        public string inter2reg_YR1RS1 { get; set; }
        public string inter2reg_YR1PC2 { get; set; }
        public string inter2reg_YR1MKS2 { get; set; }
        public string inter2reg_YR1IND2 { get; set; }
        public string inter2reg_YR1RS2 { get; set; }
        public string inter2reg_YR1PC3 { get; set; }
        public string inter2reg_YR1MKS3 { get; set; }
        public string inter2reg_YR1IND3 { get; set; }
        public string inter2reg_YR1RS3 { get; set; }
        public string inter2reg_YR1PC4 { get; set; }
        public string inter2reg_YR1MKS4 { get; set; }
        public string inter2reg_YR1IND4 { get; set; }
        public string inter2reg_YR1RS4 { get; set; }
        public string inter2reg_YR1PC5 { get; set; }
        public string inter2reg_YR1MKS5 { get; set; }
        public string inter2reg_YR1IND5 { get; set; }
        public string inter2reg_YR1RS5 { get; set; }
        public string inter2reg_YR1PC6 { get; set; }
        public string inter2reg_YR1MKS6 { get; set; }
        public string inter2reg_YR1IND6 { get; set; }
        public string inter2reg_YR1RS6 { get; set; }
        public string inter2reg_YR2PC1 { get; set; }
        public string inter2reg_YR2MKS1 { get; set; }
        public string inter2reg_YR2IND1 { get; set; }
        public string inter2reg_YR2RS1 { get; set; }
        public string inter2reg_YR2PC2 { get; set; }
        public string inter2reg_YR2MKS2 { get; set; }
        public string inter2reg_YR2IND2 { get; set; }
        public string inter2reg_YR2RS2 { get; set; }
        public string inter2reg_YR2PC3 { get; set; }
        public string inter2reg_YR2MKS3 { get; set; }
        public string inter2reg_YR2IND3 { get; set; }
        public string inter2reg_YR2RS3 { get; set; }
        public string inter2reg_YR2PC4 { get; set; }
        public string inter2reg_YR2MKS4 { get; set; }
        public string inter2reg_YR2IND4 { get; set; }
        public string inter2reg_YR2RS4 { get; set; }
        public string inter2reg_YR2PC5 { get; set; }
        public string inter2reg_YR2MKS5 { get; set; }
        public string inter2reg_YR2IND5 { get; set; }
        public string inter2reg_YR2RS5 { get; set; }
        public string inter2reg_YR2PC6 { get; set; }
        public string inter2reg_YR2MKS6 { get; set; }
        public string inter2reg_YR2IND6 { get; set; }
        public string inter2reg_YR2RS6 { get; set; }
        public string inter2reg_YR2PC7 { get; set; }
        public string inter2reg_YR2MKS7 { get; set; }
        public string inter2reg_YR2IND7 { get; set; }
        public string inter2reg_YR2RS7 { get; set; }
        public string inter2reg_YR2PC8 { get; set; }
        public string inter2reg_YR2MKS8 { get; set; }
        public string inter2reg_YR2IND8 { get; set; }
        public string inter2reg_YR2RS8 { get; set; }
        public string inter2reg_YR2PC9 { get; set; }
        public string inter2reg_YR2MKS9 { get; set; }
        public string inter2reg_YR2IND9 { get; set; }
        public string inter2reg_YR2RS9 { get; set; }
        public string inter2reg_YR2PC10 { get; set; }
        public string inter2reg_YR2MKS10 { get; set; }
        public string inter2reg_YR2IND10 { get; set; }
        public string inter2reg_YR2RS10 { get; set; }
        public string inter2reg_TOTAL { get; set; }
        public string inter2reg_RESULT { get; set; }
        public string inter2reg_ADD_FLG { get; set; }
        public string inter2reg_LINKNO { get; set; }
        public System.DateTime inter2reg_CreatedDate { get; set; }
    }
}
