//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class rslt_SubjectsMaster
    {
        public int sbjct_Sno { get; set; }
        public string sbjct_ID { get; set; }
        public string sbjct_Name { get; set; }
        public Nullable<int> sbjct_CourseID { get; set; }
        public System.DateTime sbjct_CreatedDate { get; set; }
        public Nullable<System.DateTime> sbjct_UpdatedDate { get; set; }
    }
}
