//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class rst_CoursesMaster
    {
        public int corse_Sno { get; set; }
        public string corse_ID { get; set; }
        public string corse_Name { get; set; }
        public Nullable<int> corse_CourseType { get; set; }
        public System.DateTime corse_CreatedDate { get; set; }
        public Nullable<System.DateTime> corse_ModifiedDate { get; set; }
    }
}
