//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class shub_enquiries
    {
        public int enq_Sno { get; set; }
        public string enq_Name { get; set; }
        public string enq_Email { get; set; }
        public string enq_PhoneNumber { get; set; }
        public string enq_Subject { get; set; }
        public string enq_Message { get; set; }
        public Nullable<System.DateTime> enq_CreatedDate { get; set; }
        public string enq_Status { get; set; }
        public string enq_Type { get; set; }
    }
}
