//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class shub_users
    {
        public int user_Id { get; set; }
        public string user_FullName { get; set; }
        public string user_Email { get; set; }
        public string user_Password { get; set; }
        public string user_AccessLevel { get; set; }
        public string user_Status { get; set; }
        public Nullable<System.DateTime> user_CreatedDate { get; set; }
        public Nullable<System.DateTime> user_UpdatedDate { get; set; }
    }
}
