//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class shub_sectiontestquestions
    {
        public long sectestqn_Id { get; set; }
        public Nullable<int> sectestqn_TestId { get; set; }
        public string sectestqn_Question { get; set; }
        public string sectestqn_OptionA { get; set; }
        public string sectestqn_OptionB { get; set; }
        public string sectestqn_OptionC { get; set; }
        public string sectestqn_OptionD { get; set; }
        public string sectestqn_Answer { get; set; }
        public System.DateTime sectestqn_CreatedDate { get; set; }
        public Nullable<System.DateTime> sectestqn_UpdatedDate { get; set; }
        public Nullable<int> sectestqn_CreatedBy { get; set; }
        public Nullable<int> sectestqn_UpdatedBy { get; set; }
    }
}
