//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class shub_pages
    {
        public int page_Id { get; set; }
        public string page_name { get; set; }
        public string page_heading { get; set; }
        public string page_content { get; set; }
        public string page_metatitle { get; set; }
        public string page_metadescription { get; set; }
        public Nullable<int> page_updatedby { get; set; }
        public Nullable<System.DateTime> page_updateddate { get; set; }
    }
}
