//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class shub_exceptions
    {
        public int ex_Sno { get; set; }
        public string ex_name { get; set; }
        public string ex_location { get; set; }
        public string ex_other { get; set; }
        public System.DateTime ex_createddate { get; set; }
    }
}
