//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class shub_students
    {
        public long std_Id { get; set; }
        public string std_FullName { get; set; }
        public string std_Gender { get; set; }
        public string std_Age { get; set; }
        public string std_Education { get; set; }
        public string std_WhoReferredUs { get; set; }
        public string std_WorkExperience { get; set; }
        public string std_CurrentWorkPosition { get; set; }
        public string std_Description { get; set; }
        public string std_Address { get; set; }
        public string std_City { get; set; }
        public string std_State { get; set; }
        public string std_Country { get; set; }
        public Nullable<System.DateTime> std_Dob { get; set; }
        public string std_Pincode { get; set; }
        public string std_Email { get; set; }
        public string std_Password { get; set; }
        public string std_PasswordStatus { get; set; }
        public string std_Email2 { get; set; }
        public string std_Phone1 { get; set; }
        public string std_Phone2 { get; set; }
        public string std_Status { get; set; }
        public string std_ProfilePic { get; set; }
        public string std_VerificationCode { get; set; }
        public Nullable<int> std_UnsuccessfulLogins { get; set; }
        public Nullable<System.DateTime> std_CreatedDate { get; set; }
        public Nullable<System.DateTime> std_UpdatedDate { get; set; }
        public Nullable<int> std_CreatedBy { get; set; }
        public Nullable<int> std_UpdatedBy { get; set; }
    }
}
