//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class shub_chapters
    {
        public int chptr_Id { get; set; }
        public Nullable<int> chptr_SectionId { get; set; }
        public string chptr_ChapterTitle { get; set; }
        public Nullable<int> chptr_SortId { get; set; }
        public string chptr_Description { get; set; }
        public string chptr_VideoLink1 { get; set; }
        public string chptr_Video1Duration { get; set; }
        public string chptr_VideoLink2 { get; set; }
        public string chptr_Video2Duration { get; set; }
        public System.DateTime chptr_CreatedDate { get; set; }
        public Nullable<System.DateTime> chptr_UpdatedDate { get; set; }
        public Nullable<int> chptr_CreatedBy { get; set; }
        public Nullable<int> chptr_UpdatedBy { get; set; }
    }
}
