//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class shub_sectiontests
    {
        public int sectiontest_Id { get; set; }
        public Nullable<int> sectiontest_SectionId { get; set; }
        public string sectiontest_Difficulty { get; set; }
        public System.DateTime sectiontest_CreatedDate { get; set; }
        public Nullable<System.DateTime> sectiontest_UpdatedDate { get; set; }
        public Nullable<int> sectiontest_CreatedBy { get; set; }
        public Nullable<int> sectiontest_UpdatedBy { get; set; }
    }
}
