//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class shub_settings
    {
        public int set_Sno { get; set; }
        public string set_Name { get; set; }
        public string set_Value { get; set; }
        public Nullable<int> set_CreatedBy { get; set; }
        public Nullable<System.DateTime> set_CreatedDate { get; set; }
        public Nullable<int> set_UpdatedBy { get; set; }
        public Nullable<System.DateTime> set_UpdatedDate { get; set; }
    }
}
