//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class shub_sectionmaterials
    {
        public int material_Id { get; set; }
        public Nullable<int> material_SectionId { get; set; }
        public string material_FileName { get; set; }
        public System.DateTime material_CreatedDate { get; set; }
    }
}
