//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class shub_coursereviews
    {
        public long crsrvw_Id { get; set; }
        public int crsrvw_CourseId { get; set; }
        public int crsrvw_StudentId { get; set; }
        public Nullable<int> crsrvw_BatchId { get; set; }
        public int crsrvw_Rating { get; set; }
        public string crsrvw_Comment { get; set; }
        public string crsrvw_Status { get; set; }
        public System.DateTime crsrvw_CreatedDate { get; set; }
        public Nullable<System.DateTime> crsrvw_UpdatedDate { get; set; }
        public string crsrvw_CreatedBy { get; set; }
        public string crsrvw_UpdatedBy { get; set; }
    }
}
