//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class shub_courses
    {
        public long course_Id { get; set; }
        public string course_Name { get; set; }
        public string course_UrlName { get; set; }
        public Nullable<float> course_Fee { get; set; }
        public string course_ShortDescription { get; set; }
        public string course_Description { get; set; }
        public string course_Status { get; set; }
        public string course_Featured { get; set; }
        public string course_Duration { get; set; }
        public string course_Logo { get; set; }
        public string course_CoverPicture { get; set; }
        public string course_Curriculum { get; set; }
        public string course_DemoLink { get; set; }
        public string course_DemoLink2 { get; set; }
        public System.DateTime course_CreatedDate { get; set; }
        public Nullable<System.DateTime> course_UpdatedDate { get; set; }
        public Nullable<int> course_CreatedBy { get; set; }
        public Nullable<int> course_UpdatedBy { get; set; }
    }
}
